# for local development
version: "3.1"

services:
  mongo:
    container_name: mapories_db
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ${DB_DATABASE:-mapories}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-user}
    volumes:
      - ./db/create-user.sh:/docker-entrypoint-initdb.d/create-user.sh:ro

  mongo-express:
    container_name: mapories_dbadm
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  redis:
    container_name: mapories_session_redis
    image: "docker.io/bitnami/redis:6.0-debian-10"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
